"""
alerter.py — Formats and sends email alerts for significant financial news.

Sends a single email per check cycle that bundles all alerts together,
grouped by instrument, to avoid inbox flooding.
"""

import logging
import smtplib
from datetime import datetime, timezone
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Any

from analyzer import AnalysisResult

logger = logging.getLogger(__name__)

# Sentiment → colour for HTML email
SENTIMENT_COLOR = {
    "positive": "#1a7340",   # dark green
    "negative": "#b91c1c",   # dark red
    "neutral":  "#4b5563",   # grey
}

SENTIMENT_LABEL = {
    "positive": "POSITIVE",
    "negative": "NEGATIVE",
    "neutral":  "NEUTRAL",
}


class EmailAlerter:
    def __init__(self, email_cfg: dict[str, Any], smtp_password: str):
        self._cfg = email_cfg
        self._password = smtp_password

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    def send_alert(self, results: list[AnalysisResult]) -> bool:
        """
        Send a single email summarising all significant articles.
        Returns True on success, False on error.
        """
        if not results:
            logger.debug("No significant articles — skipping email.")
            return True

        subject = self._build_subject(results)
        html_body = self._build_html(results)
        plain_body = self._build_plain(results)

        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = self._cfg["from_address"]
        msg["To"] = ", ".join(self._cfg["to_addresses"])
        msg.attach(MIMEText(plain_body, "plain"))
        msg.attach(MIMEText(html_body, "html"))

        return self._send(msg)

    # ------------------------------------------------------------------
    # Subject line
    # ------------------------------------------------------------------

    def _build_subject(self, results: list[AnalysisResult]) -> str:
        prefix = self._cfg.get("subject_prefix", "[FinNews]")
        tickers = sorted({r.instrument_ticker for r in results})
        sentiments = {r.sentiment for r in results}

        if sentiments == {"positive"}:
            direction = "Positive"
        elif sentiments == {"negative"}:
            direction = "Negative"
        else:
            direction = "Mixed"

        count = len(results)
        ticker_str = ", ".join(tickers[:4])
        if len(tickers) > 4:
            ticker_str += f" +{len(tickers) - 4} more"

        return f"{prefix} {direction} news ({count} alert{'s' if count > 1 else ''}) — {ticker_str}"

    # ------------------------------------------------------------------
    # HTML body
    # ------------------------------------------------------------------

    def _build_html(self, results: list[AnalysisResult]) -> str:
        grouped = _group_by_instrument(results)
        now_str = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        cards = []
        for ticker, articles in grouped.items():
            name = articles[0].instrument_name
            article_html = "\n".join(self._article_card(a) for a in articles)
            cards.append(f"""
            <div style="margin-bottom:28px;">
              <h2 style="font-family:sans-serif;font-size:16px;font-weight:700;
                         color:#111827;border-bottom:2px solid #e5e7eb;
                         padding-bottom:6px;margin-bottom:12px;">
                {name} <span style="color:#6b7280;font-weight:400;">({ticker})</span>
              </h2>
              {article_html}
            </div>
            """)

        body = "\n".join(cards)

        return f"""
        <!DOCTYPE html>
        <html lang="en">
        <head><meta charset="UTF-8"></head>
        <body style="background:#f9fafb;padding:24px;font-family:sans-serif;">
          <div style="max-width:680px;margin:0 auto;background:#fff;
                      border-radius:8px;padding:28px;
                      box-shadow:0 1px 3px rgba(0,0,0,0.1);">
            <h1 style="font-size:20px;color:#111827;margin-top:0;">
              Financial News Alert
              <span style="font-size:13px;font-weight:400;color:#6b7280;
                           margin-left:12px;">{now_str}</span>
            </h1>
            {body}
            <p style="font-size:11px;color:#9ca3af;margin-top:24px;
                      border-top:1px solid #f3f4f6;padding-top:12px;">
              Generated by Financial News Monitor &middot; Powered by Claude Opus 4.6
            </p>
          </div>
        </body>
        </html>
        """

    def _article_card(self, result: AnalysisResult) -> str:
        color = SENTIMENT_COLOR.get(result.sentiment, "#4b5563")
        label = SENTIMENT_LABEL.get(result.sentiment, "NEUTRAL")
        conf_pct = int(result.confidence * 100)

        points_html = ""
        if result.key_points:
            li_items = "".join(f"<li style='margin:4px 0;'>{p}</li>" for p in result.key_points)
            points_html = f"<ul style='margin:8px 0 0 0;padding-left:20px;color:#374151;font-size:13px;'>{li_items}</ul>"

        pub_time = _fmt_unix(result.article_datetime)

        return f"""
        <div style="border:1px solid #e5e7eb;border-radius:6px;
                    padding:14px;margin-bottom:12px;">
          <div style="display:flex;align-items:center;gap:8px;margin-bottom:8px;">
            <span style="background:{color};color:#fff;font-size:11px;font-weight:700;
                         padding:2px 8px;border-radius:12px;letter-spacing:.5px;">
              {label}
            </span>
            <span style="font-size:11px;color:#6b7280;">
              Confidence: {conf_pct}% &middot; {result.source} &middot; {pub_time}
            </span>
          </div>
          <a href="{result.url}" style="font-size:14px;font-weight:600;color:#1d4ed8;
                                        text-decoration:none;">
            {result.headline}
          </a>
          <p style="font-size:13px;color:#374151;margin:8px 0 0 0;">
            {result.impact_summary}
          </p>
          {points_html}
        </div>
        """

    # ------------------------------------------------------------------
    # Plain-text fallback
    # ------------------------------------------------------------------

    def _build_plain(self, results: list[AnalysisResult]) -> str:
        grouped = _group_by_instrument(results)
        now_str = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        lines = [f"Financial News Alert — {now_str}", "=" * 60, ""]

        for ticker, articles in grouped.items():
            name = articles[0].instrument_name
            lines.append(f"{name} ({ticker})")
            lines.append("-" * 40)
            for a in articles:
                pub_time = _fmt_unix(a.article_datetime)
                lines.append(f"[{a.sentiment.upper()} {int(a.confidence*100)}%] {a.headline}")
                lines.append(f"  Source: {a.source} | {pub_time}")
                lines.append(f"  {a.impact_summary}")
                for pt in a.key_points:
                    lines.append(f"  • {pt}")
                lines.append(f"  URL: {a.url}")
                lines.append("")
            lines.append("")

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # SMTP send
    # ------------------------------------------------------------------

    def _send(self, msg: MIMEMultipart) -> bool:
        host = self._cfg["smtp_host"]
        port = int(self._cfg["smtp_port"])
        use_tls = bool(self._cfg.get("use_tls", True))
        sender = self._cfg["from_address"]

        try:
            with smtplib.SMTP(host, port, timeout=15) as server:
                if use_tls:
                    server.starttls()
                server.login(sender, self._password)
                server.sendmail(sender, self._cfg["to_addresses"], msg.as_string())
            logger.info("Alert email sent to %s", self._cfg["to_addresses"])
            return True
        except smtplib.SMTPAuthenticationError:
            logger.error(
                "SMTP auth failed — check SMTP_PASSWORD and that you're using "
                "an App Password if using Gmail with 2FA."
            )
            return False
        except smtplib.SMTPException as exc:
            logger.error("SMTP error: %s", exc)
            return False
        except OSError as exc:
            logger.error("Network error sending email: %s", exc)
            return False


# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------

def _group_by_instrument(
    results: list[AnalysisResult],
) -> dict[str, list[AnalysisResult]]:
    grouped: dict[str, list[AnalysisResult]] = {}
    for r in results:
        grouped.setdefault(r.instrument_ticker, []).append(r)
    return grouped


def _fmt_unix(ts: int) -> str:
    if not ts:
        return "unknown time"
    try:
        return datetime.fromtimestamp(ts, tz=timezone.utc).strftime("%b %d %H:%M UTC")
    except (ValueError, OSError):
        return "unknown time"
