"""
alerter.py — Formats and sends email alerts for financial news and price swings.

Sends a single email per check cycle that bundles all alerts together,
grouped by instrument, to avoid inbox flooding.
"""

import logging
import smtplib
from datetime import datetime, timezone
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Any

from analyzer import Alert

logger = logging.getLogger(__name__)


class EmailAlerter:
    def __init__(self, email_cfg: dict[str, Any], smtp_password: str):
        self._cfg = email_cfg
        self._password = smtp_password

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    def send_alert(self, alerts: list[Alert]) -> bool:
        """Send a single email summarising all alerts. Returns True on success."""
        if not alerts:
            return True

        subject = self._build_subject(alerts)
        html_body = self._build_html(alerts)
        plain_body = self._build_plain(alerts)

        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = self._cfg["from_address"]
        msg["To"] = ", ".join(self._cfg["to_addresses"])
        msg.attach(MIMEText(plain_body, "plain"))
        msg.attach(MIMEText(html_body, "html"))

        return self._send(msg)

    # ------------------------------------------------------------------
    # Subject line
    # ------------------------------------------------------------------

    def _build_subject(self, alerts: list[Alert]) -> str:
        prefix = self._cfg.get("subject_prefix", "[FinNews]")
        tickers = sorted({a.ticker for a in alerts})
        ticker_str = ", ".join(tickers[:4])
        if len(tickers) > 4:
            ticker_str += f" +{len(tickers) - 4} more"

        news_count = sum(1 for a in alerts if a.kind == "news")
        swing_count = sum(1 for a in alerts if a.kind == "price_swing")

        parts = []
        if news_count:
            parts.append(f"{news_count} news")
        if swing_count:
            parts.append(f"{swing_count} price swing{'s' if swing_count > 1 else ''}")

        summary = " + ".join(parts)
        return f"{prefix} {summary} — {ticker_str}"

    # ------------------------------------------------------------------
    # HTML body
    # ------------------------------------------------------------------

    def _build_html(self, alerts: list[Alert]) -> str:
        grouped = _group_by_instrument(alerts)
        now_str = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        cards = []
        for ticker, instrument_alerts in grouped.items():
            name = instrument_alerts[0].name
            cards_html = "\n".join(self._alert_card(a) for a in instrument_alerts)
            cards.append(f"""
            <div style="margin-bottom:28px;">
              <h2 style="font-family:sans-serif;font-size:16px;font-weight:700;
                         color:#111827;border-bottom:2px solid #e5e7eb;
                         padding-bottom:6px;margin-bottom:12px;">
                {name} <span style="color:#6b7280;font-weight:400;">({ticker})</span>
              </h2>
              {cards_html}
            </div>
            """)

        body = "\n".join(cards)

        return f"""
        <!DOCTYPE html>
        <html lang="en">
        <head><meta charset="UTF-8"></head>
        <body style="background:#f9fafb;padding:24px;font-family:sans-serif;">
          <div style="max-width:680px;margin:0 auto;background:#fff;
                      border-radius:8px;padding:28px;
                      box-shadow:0 1px 3px rgba(0,0,0,0.1);">
            <h1 style="font-size:20px;color:#111827;margin-top:0;">
              Financial Alert
              <span style="font-size:13px;font-weight:400;color:#6b7280;
                           margin-left:12px;">{now_str}</span>
            </h1>
            {body}
            <p style="font-size:11px;color:#9ca3af;margin-top:24px;
                      border-top:1px solid #f3f4f6;padding-top:12px;">
              Generated by Financial News Monitor
            </p>
          </div>
        </body>
        </html>
        """

    def _alert_card(self, alert: Alert) -> str:
        if alert.kind == "price_swing":
            return self._price_swing_card(alert)
        return self._news_card(alert)

    def _news_card(self, alert: Alert) -> str:
        pub_time = _fmt_unix(alert.article_datetime)
        return f"""
        <div style="border:1px solid #e5e7eb;border-radius:6px;
                    padding:14px;margin-bottom:12px;">
          <div style="margin-bottom:8px;">
            <span style="background:#1d4ed8;color:#fff;font-size:11px;font-weight:700;
                         padding:2px 8px;border-radius:12px;letter-spacing:.5px;">
              NEWS
            </span>
            <span style="font-size:11px;color:#6b7280;margin-left:8px;">
              {alert.source} &middot; {pub_time}
            </span>
          </div>
          <a href="{alert.url}" style="font-size:14px;font-weight:600;color:#1d4ed8;
                                       text-decoration:none;">
            {alert.headline}
          </a>
        </div>
        """

    def _price_swing_card(self, alert: Alert) -> str:
        is_up = alert.direction == "up"
        color = "#1a7340" if is_up else "#b91c1c"
        arrow = "UP" if is_up else "DOWN"
        sign = "+" if is_up else ""
        return f"""
        <div style="border:1px solid #e5e7eb;border-radius:6px;
                    padding:14px;margin-bottom:12px;">
          <div style="margin-bottom:8px;">
            <span style="background:{color};color:#fff;font-size:11px;font-weight:700;
                         padding:2px 8px;border-radius:12px;letter-spacing:.5px;">
              PRICE {arrow}
            </span>
          </div>
          <p style="font-size:14px;font-weight:600;color:#111827;margin:0;">
            {alert.name} ({alert.ticker})
          </p>
          <p style="font-size:13px;color:{color};font-weight:700;margin:6px 0 0 0;">
            {sign}{alert.change_pct:.2f}% &nbsp;&middot;&nbsp;
            <span style="color:#374151;font-weight:400;">
              Current price: {alert.current_price:.2f}
            </span>
          </p>
        </div>
        """

    # ------------------------------------------------------------------
    # Plain-text fallback
    # ------------------------------------------------------------------

    def _build_plain(self, alerts: list[Alert]) -> str:
        grouped = _group_by_instrument(alerts)
        now_str = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        lines = [f"Financial Alert — {now_str}", "=" * 60, ""]

        for ticker, instrument_alerts in grouped.items():
            name = instrument_alerts[0].name
            lines.append(f"{name} ({ticker})")
            lines.append("-" * 40)
            for a in instrument_alerts:
                if a.kind == "news":
                    pub_time = _fmt_unix(a.article_datetime)
                    lines.append(f"[NEWS] {a.headline}")
                    lines.append(f"  Source: {a.source} | {pub_time}")
                    lines.append(f"  URL: {a.url}")
                else:
                    sign = "+" if a.direction == "up" else ""
                    lines.append(
                        f"[PRICE {a.direction.upper()}] "
                        f"{sign}{a.change_pct:.2f}% | Current: {a.current_price:.2f}"
                    )
                lines.append("")
            lines.append("")

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # SMTP send
    # ------------------------------------------------------------------

    def _send(self, msg: MIMEMultipart) -> bool:
        host = self._cfg["smtp_host"]
        port = int(self._cfg["smtp_port"])
        use_tls = bool(self._cfg.get("use_tls", True))
        sender = self._cfg["from_address"]

        try:
            with smtplib.SMTP(host, port, timeout=15) as server:
                if use_tls:
                    server.starttls()
                server.login(sender, self._password)
                server.sendmail(sender, self._cfg["to_addresses"], msg.as_string())
            logger.info("Alert email sent to %s", self._cfg["to_addresses"])
            return True
        except smtplib.SMTPAuthenticationError:
            logger.error(
                "SMTP auth failed — check SMTP_PASSWORD and that you're using "
                "an App Password if using Gmail with 2FA."
            )
            return False
        except smtplib.SMTPException as exc:
            logger.error("SMTP error: %s", exc)
            return False
        except OSError as exc:
            logger.error("Network error sending email: %s", exc)
            return False


# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------

def _group_by_instrument(alerts: list[Alert]) -> dict[str, list[Alert]]:
    grouped: dict[str, list[Alert]] = {}
    for a in alerts:
        grouped.setdefault(a.ticker, []).append(a)
    return grouped


def _fmt_unix(ts: int) -> str:
    if not ts:
        return "unknown time"
    try:
        return datetime.fromtimestamp(ts, tz=timezone.utc).strftime("%b %d %H:%M UTC")
    except (ValueError, OSError):
        return "unknown time"
